service: vermilion 
# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details

custom:
  deploymentBucket: ${env:DEPLOYMENT_BUCKET}
  crawlerRole: "arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/service-role/AWSGlueServiceRole-Crawler"
  bucket: ${env:BUCKET}

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  deploymentBucket: ${self:custom.deploymentBucket}
	iamRoleStatements:
    - Effect: Allow
      Action:
         - s3:GetObject
         - s3:GetObjectAcl
      Resource: "arn:aws:s3:::${self:custom.deploymentBucket}/*"
	vpc:
      securityGroupIds:
        - sg-00e571fe3
      subnetIds:
        - subnet-03bbfe9
        - subnet-0f79559

package:
 include:
   - lake/**
 exclude:
   - .git/**

functions:
  crawler:
    handler: handlers.crawler
    description: This is responsable for read S3 path then create crawlers and tables to be used by Athena
    memorySize: 128
    events:
      - schedule: rate(24 hours)
    environment:
      CRAWLER_ROLE: ${self:custom.crawlerRole}
      BUCKET: ${self:custom.bucket}

# resources:
#   Resources:
#     S3BucketOutputs:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: ${self:bucket.output}

plugins:
  - serverless-python-requirements
