service: vermilion 
# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details

custom:
  namespace: ${opt:stage}
  deploymentBucket: ${env:DEPLOYMENT_BUCKET}
  crawlerRole: ${env:CRAWLER_ROLE, "arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/AWSGlueServiceRole-Crawler"}
  awsAccountId: ${env:AWS_ACCOUNT_ID}
  bucket: ${env:BUCKET}
  profile: ${opt:profile, 'default'}
  region: ${env:REGION, 'us-east-1'}
provider:
  name: aws
  runtime: python3.7
  stage: dev
  timeout: 60 # optional, in seconds, default is 6
  profile: ${self:custom.profile}
  region: ${self:custom.region}
  deploymentBucket: ${self:custom.deploymentBucket}
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #        - s3:GetObject
  #        - s3:ListBucket
  #        - s3:ListObjects
  #        - s3:GetObjectAcl
  #     Resource: "arn:aws:s3:::${self:custom.bucket}/*"
  #   - Effect: Allow
  #     Action:
  #        - glue:CreateCrawler
  #        - glue:StartCrawler
  #     Resource: "arn:aws:glue:::crawler/*"
  #
  #   - Effect: Allow
  #     Action:
  #        - glue:CreateDatabase
  #        - glue:GetDatabases
  #        - glue:CreateTable
  #     Resource:
  #        - "arn:aws:glue:::table/*/*"
  #        - "arn:aws:glue:::database/*"
  #        - "arn:aws:glue:::catalog" 
package:
 include:
   - lake/**
 exclude:
   - .git/**

functions:
  crawler:
    handler: handlers.crawler
    description: This is responsable for read S3 path then create crawlers and tables to be used by Athena
    memorySize: 128
    role: ${self:custom.crawlerRole}
    events:
      - schedule: rate(2 hours)
    environment:
      APP_NAMESPACE: ${self:custom.namespace}
      APP_CRAWLER_ROLE: ${self:custom.crawlerRole}
      APP_BUCKET: ${self:custom.bucket}

plugins:
  - serverless-python-requirements
